### ISSUE TITLE
Invitation to join the Highlight.js grammar maintainers team

### ISSUE THREAD

**Issue by joshgoebel** [chapel-lang/highlightjs-chapel#5]
Re: Invitation to join the Highlight.js grammar-maintainers team

I'd like to invite the grammar maintainer/maintainers to our `@highlightjs/grammar-maintainers` Team... But I don't know who to invite... this is used to ping grammar maintainers about big upcoming changes or get their feedback on things that may affect them in the future.

**Comment by bradcray** [comment]
Hi @joshgoebel — I'd probably be the person to add to this, at least for the time being.  If it's more than I end up having the bandwidth for, I'll try to find someone else to help out.

**Comment by joshgoebel** [comment]
Invited!  Thanks!
