### ISSUE TITLE
release plug-in as NPM package

### ISSUE THREAD

**Issue by lucaferranti** [chapel-lang/highlightjs-chapel#8]
It is great to have highlight support for Chapel. As an improvement, may I suggest to register this to NPM as a package. It would allow to seamlessly install and use the plug-in in other webpages and platforms.

I think the following steps should make the trick:
1. Run `npm init` to interactively generate a `package.json`
2. Create an npm account
3. Login with `npm login`
4. Run `npm publish`

**Comment by lucaferranti** [comment]
For example, this would be needed to support syntax highlight on the chapel track on exercism. As a side note, this would also greatly simplify the instructions in the readme to use the plug-in.

Alternatively, I could fork this and register my fork and regularly check for upstream updates, but that's maybe a little clumsy as solution?

**Comment by bradcray** [comment]
@lucaferranti : Apologies for the lack of a previous response here...  We don't generally receive notifications for new issues posted on this repo, it seems.  I'm not familiar with NPM package registration.  Would something prevent you from being able to register the original repo rather than a personal fork?

**Comment by lucaferranti** [comment]
I would be pretty surprised (and shocked) if I npm allowed me to register a repository I don't have write access to.

I can try and update if (hopefully when) I get some permission denied error

**Comment by bradcray** [comment]
Definitely let us know what you learn.  I don't know enough about npm to have any intuition.  We could also consider discussing the team's level of comfort giving you write permission to this repo.

**Comment by lucaferranti** [comment]
Thanks @bradcray for merging the pull request.

As discussed above, I tried to register this on NPM and it went through :tada:  
https://www.npmjs.com/package/highlightjs-chapel

**Comment by bradcray** [comment]
Great!  Sorry it took me so long to get to it.

Is there more that needs to be done to close/resolve this issue?

**Comment by lucaferranti** [comment]
I think this can be closed now. I'll check on the exercism side if I can get syntax highlight integrated and working
